services:
  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - "8080:8080"
    volumes:
      - "./secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro"
      - "data:/home/opuser/.op/data"
    restart: unless-stopped
  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - "./secrets/1password-credentials.json:/home/opuser/.op/1password-credentials.json:ro"
      - "data:/home/opuser/.op/data"
    restart: unless-stopped
volumes:
  data:
